from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Mapping


def build_playback_readiness_snapshot(playback_plan: Mapping[str, Any] | None, *, timestamp: str | None = None) -> dict[str, Any]:
    plan = dict(playback_plan or {})
    selected_source = dict(plan.get("selected_source") or {})
    browser_runtime = dict(plan.get("browser_runtime") or {})
    external_runtime = dict(plan.get("external_runtime") or {})
    diagnostics = dict(plan.get("runtime_diagnostics") or {})
    preflight = dict(plan.get("runtime_preflight") or {})
    browser_bridge = dict(plan.get("browser_runtime_bridge") or {})
    browser_capabilities = dict(browser_bridge.get("capability_snapshot") or {})
    browser_sandbox = dict(browser_bridge.get("sandbox") or {})
    browser_bootstrap = dict(browser_bridge.get("bootstrap") or {})
    execution_runtime = dict(browser_bridge.get("execution_runtime") or {})
    execution_metrics = dict(plan.get("execution_metrics") or execution_runtime.get("execution_metrics") or {})
    execution_timeline = dict(plan.get("execution_timeline") or execution_runtime.get("execution_timeline") or {})
    recovery_path = dict(plan.get("recovery_path") or execution_runtime.get("recovery_path") or {})
    runtime_grade = dict(plan.get("runtime_grade") or execution_runtime.get("runtime_grade") or {})
    coordination_metrics = dict(plan.get("coordination_metrics") or {})
    runtime_negotiation = dict(plan.get("runtime_negotiation") or {})
    adaptive_strategy = dict(plan.get("adaptive_strategy") or {})
    orchestration_graph = dict(plan.get("orchestration_graph") or {})
    fallback_negotiation = dict(plan.get("fallback_negotiation") or {})
    return {
        "selected_source_id": str(selected_source.get("source_fingerprint") or "").strip(),
        "selected_source": {
            "mobile_friendly": bool(selected_source.get("mobile_friendly")),
            "quality_label": str(selected_source.get("quality_label") or selected_source.get("resolution") or "").strip(),
            "codec": str(selected_source.get("codec") or selected_source.get("video_codec") or "").strip(),
            "source_type": str(selected_source.get("source_type") or selected_source.get("release_type") or "").strip(),
        },
        "runtime_profile": str(plan.get("runtime_profile") or "").strip(),
        "playback_runtime": str(plan.get("playback_runtime") or "").strip(),
        "runtime_mode": str(plan.get("runtime_mode") or "").strip(),
        "runtime_state": str(plan.get("runtime_state") or "").strip(),
        "startup_confidence": str(plan.get("startup_confidence") or "").strip(),
        "browser_readiness": str(browser_runtime.get("readiness") or plan.get("playback_readiness") or "").strip(),
        "external_fallback_available": bool(external_runtime.get("readiness") == "external_ready"),
        "warnings": _json_safe_strings(plan.get("runtime_warnings") or []),
        "timestamp": str(timestamp or _now_iso8601()),
        "fallback_reason": str(diagnostics.get("fallback_reason") or "").strip(),
        "fallback_strategy": str(preflight.get("fallback_strategy") or "").strip(),
        "runtime_blocking_reasons": _json_safe_strings(preflight.get("blocking_reasons") or []),
        "experimental_browser_runtime": {
            "bridge_mode": str(browser_bridge.get("bridge_mode") or "").strip(),
            "browser_viability": str(browser_capabilities.get("startup_viability") or "").strip(),
            "sandbox_status": str(browser_sandbox.get("sandbox_status") or "").strip(),
            "degradation_warnings": _json_safe_strings(browser_capabilities.get("degradation_warnings") or []),
            "fallback_runtime": str(browser_bootstrap.get("fallback_runtime") or "").strip(),
        },
        "execution_state": str(plan.get("execution_state") or execution_runtime.get("execution_state") or "").strip(),
        "simulated_runtime_health": str(plan.get("simulated_runtime_health") or execution_runtime.get("simulated_runtime_health") or "").strip(),
        "execution_metrics": dict(execution_metrics),
        "execution_timeline": dict(execution_timeline),
        "recovery_path": dict(recovery_path),
        "runtime_grade": dict(runtime_grade),
        "execution_events": [dict(item) for item in (plan.get("execution_events") or execution_runtime.get("execution_events") or []) if isinstance(item, dict)],
        "readiness_meter": int(plan.get("readiness_meter", 0) or 0),
        "coordination_state": str(plan.get("coordination_state") or "").strip(),
        "coordination_metrics": coordination_metrics,
        "runtime_negotiation": runtime_negotiation,
        "adaptive_strategy": adaptive_strategy,
        "orchestration_graph": orchestration_graph,
        "fallback_negotiation": fallback_negotiation,
        "runtime_predictions": dict(plan.get("runtime_predictions") or {}),
        "runtime_memory_summary": dict(plan.get("runtime_memory_summary") or {}),
        "adaptation_history": dict(plan.get("adaptation_history") or {}),
        "confidence_evolution": dict(plan.get("confidence_evolution") or {}),
        "runtime_reputation": dict(plan.get("runtime_reputation") or {}),
        "orchestration_forecast": dict(plan.get("orchestration_forecast") or {}),
        "intelligence_metrics": dict(plan.get("intelligence_metrics") or {}),
        "runtime_identity": dict(plan.get("runtime_identity") or {}),
        "orchestration_archetype": str(plan.get("orchestration_archetype") or "").strip(),
        "runtime_temperament": str(plan.get("runtime_temperament") or "").strip(),
        "adaptation_profile": str(plan.get("adaptation_profile") or "").strip(),
        "behavioral_drift": dict(plan.get("behavioral_drift") or {}),
        "continuity_state": dict(plan.get("continuity_state") or {}),
        "identity_confidence": int(plan.get("identity_confidence", 0) or 0),
        "identity_forecast": dict(plan.get("identity_forecast") or {}),
        "persistent_traits": _json_safe_strings(plan.get("persistent_traits") or []),
        "orchestration_traits": _json_safe_strings(plan.get("orchestration_traits") or []),
        "identity_metrics": dict(plan.get("identity_metrics") or {}),
        "identity_warnings": _json_safe_strings(plan.get("identity_warnings") or []),
        "runtime_ecosystem": dict(plan.get("runtime_ecosystem") or {}),
        "ecosystem_balance": dict(plan.get("ecosystem_balance") or {}),
        "orchestration_pressure": dict(plan.get("orchestration_pressure") or {}),
        "runtime_clusters": dict(plan.get("runtime_clusters") or {}),
        "stability_zone": dict(plan.get("stability_zone") or {}),
        "ecosystem_climate": dict(plan.get("ecosystem_climate") or {}),
        "degradation_currents": dict(plan.get("degradation_currents") or {}),
        "resilience_topology": dict(plan.get("resilience_topology") or {}),
        "adaptive_equilibrium": dict(plan.get("adaptive_equilibrium") or {}),
        "ecosystem_forecast": dict(plan.get("ecosystem_forecast") or {}),
        "ecosystem_governance": dict(plan.get("ecosystem_governance") or {}),
        "ecosystem_metrics": dict(plan.get("ecosystem_metrics") or {}),
        "ecosystem_events": [dict(item) for item in (plan.get("ecosystem_events") or []) if isinstance(item, dict)],
        "ecosystem_memory": dict(plan.get("ecosystem_memory") or {}),
        "runtime_cinema": dict(plan.get("runtime_cinema") or {}),
        "cinematic_direction": dict(plan.get("cinematic_direction") or {}),
        "runtime_pacing": dict(plan.get("runtime_pacing") or {}),
        "immersion_state": dict(plan.get("immersion_state") or {}),
        "runtime_atmosphere": dict(plan.get("runtime_atmosphere") or {}),
        "dramatic_tension": dict(plan.get("dramatic_tension") or {}),
        "continuity_cinema": dict(plan.get("continuity_cinema") or {}),
        "orchestration_mood": dict(plan.get("orchestration_mood") or {}),
        "scene_energy": dict(plan.get("scene_energy") or {}),
        "cinematic_balance": dict(plan.get("cinematic_balance") or {}),
        "runtime_aesthetics": dict(plan.get("runtime_aesthetics") or {}),
        "cinematic_forecast": dict(plan.get("cinematic_forecast") or {}),
        "cinematic_governance": dict(plan.get("cinematic_governance") or {}),
        "cinematic_metrics": dict(plan.get("cinematic_metrics") or {}),
        "cinematic_events": [dict(item) for item in (plan.get("cinematic_events") or []) if isinstance(item, dict)],
        "cinematic_memory": dict(plan.get("cinematic_memory") or {}),
        "runtime_consciousness": dict(plan.get("runtime_consciousness") or {}),
        "awareness_state": dict(plan.get("awareness_state") or {}),
        "orchestration_attention": dict(plan.get("orchestration_attention") or {}),
        "continuity_awareness": dict(plan.get("continuity_awareness") or {}),
        "runtime_reflection": dict(plan.get("runtime_reflection") or {}),
        "orchestration_intuition": dict(plan.get("orchestration_intuition") or {}),
        "cognitive_balance": dict(plan.get("cognitive_balance") or {}),
        "awareness_pressure": dict(plan.get("awareness_pressure") or {}),
        "orchestration_focus": dict(plan.get("orchestration_focus") or {}),
        "runtime_presence": dict(plan.get("runtime_presence") or {}),
        "orchestration_perception": dict(plan.get("orchestration_perception") or {}),
        "consciousness_forecast": dict(plan.get("consciousness_forecast") or {}),
        "consciousness_governance": dict(plan.get("consciousness_governance") or {}),
        "consciousness_metrics": dict(plan.get("consciousness_metrics") or {}),
        "consciousness_events": [dict(item) for item in (plan.get("consciousness_events") or []) if isinstance(item, dict)],
        "consciousness_memory": dict(plan.get("consciousness_memory") or {}),
        "runtime_instinct": dict(plan.get("runtime_instinct") or {}),
        "stabilization_instinct": dict(plan.get("stabilization_instinct") or {}),
        "resilience_instinct": dict(plan.get("resilience_instinct") or {}),
        "fallback_instinct": dict(plan.get("fallback_instinct") or {}),
        "continuity_instinct": dict(plan.get("continuity_instinct") or {}),
        "cinematic_instinct": dict(plan.get("cinematic_instinct") or {}),
        "equilibrium_instinct": dict(plan.get("equilibrium_instinct") or {}),
        "orchestration_reflexes": dict(plan.get("orchestration_reflexes") or {}),
        "instinct_pressure": dict(plan.get("instinct_pressure") or {}),
        "adaptive_instinct": dict(plan.get("adaptive_instinct") or {}),
        "runtime_survival": dict(plan.get("runtime_survival") or {}),
        "instinct_forecast": dict(plan.get("instinct_forecast") or {}),
        "instinct_governance": dict(plan.get("instinct_governance") or {}),
        "instinct_metrics": dict(plan.get("instinct_metrics") or {}),
        "instinct_events": [dict(item) for item in (plan.get("instinct_events") or []) if isinstance(item, dict)],
        "instinct_memory": dict(plan.get("instinct_memory") or {}),
        "runtime_subconscious": dict(plan.get("runtime_subconscious") or {}),
        "latent_patterns": dict(plan.get("latent_patterns") or {}),
        "orchestration_underflow": dict(plan.get("orchestration_underflow") or {}),
        "hidden_equilibrium": dict(plan.get("hidden_equilibrium") or {}),
        "subconscious_pressure": dict(plan.get("subconscious_pressure") or {}),
        "silent_adaptation": dict(plan.get("silent_adaptation") or {}),
        "continuity_underlayers": dict(plan.get("continuity_underlayers") or {}),
        "orchestration_residue": dict(plan.get("orchestration_residue") or {}),
        "dormant_resilience": dict(plan.get("dormant_resilience") or {}),
        "cinematic_underflow": dict(plan.get("cinematic_underflow") or {}),
        "orchestration_echoes": dict(plan.get("orchestration_echoes") or {}),
        "subconscious_forecast": dict(plan.get("subconscious_forecast") or {}),
        "subconscious_governance": dict(plan.get("subconscious_governance") or {}),
        "subconscious_metrics": dict(plan.get("subconscious_metrics") or {}),
        "subconscious_events": [dict(item) for item in (plan.get("subconscious_events") or []) if isinstance(item, dict)],
        "subconscious_memory": dict(plan.get("subconscious_memory") or {}),
        "runtime_dreaming": dict(plan.get("runtime_dreaming") or {}),
        "cinematic_dreams": dict(plan.get("cinematic_dreams") or {}),
        "orchestration_visions": dict(plan.get("orchestration_visions") or {}),
        "latent_projection": dict(plan.get("latent_projection") or {}),
        "stabilization_dreams": dict(plan.get("stabilization_dreams") or {}),
        "resilience_dreams": dict(plan.get("resilience_dreams") or {}),
        "continuity_dreams": dict(plan.get("continuity_dreams") or {}),
        "subconscious_projection": dict(plan.get("subconscious_projection") or {}),
        "dormant_pathways": dict(plan.get("dormant_pathways") or {}),
        "adaptive_dreaming": dict(plan.get("adaptive_dreaming") or {}),
        "runtime_mirroring": dict(plan.get("runtime_mirroring") or {}),
        "dream_forecast": dict(plan.get("dream_forecast") or {}),
        "dream_governance": dict(plan.get("dream_governance") or {}),
        "dream_metrics": dict(plan.get("dream_metrics") or {}),
        "dream_events": [dict(item) for item in (plan.get("dream_events") or []) if isinstance(item, dict)],
        "dreaming_memory": dict(plan.get("dreaming_memory") or {}),
        "runtime_federation": dict(plan.get("runtime_federation") or {}),
        "federation_state": dict(plan.get("federation_state") or {}),
        "federation_projection": dict(plan.get("federation_projection") or {}),
        "federation_forecast": dict(plan.get("federation_forecast") or {}),
        "federation_governance": dict(plan.get("federation_governance") or {}),
        "federation_continuity": dict(plan.get("federation_continuity") or {}),
        "federation_metrics": dict(plan.get("federation_metrics") or {}),
        "federation_events": [dict(item) for item in (plan.get("federation_events") or []) if isinstance(item, dict)],
        "federation_coherence": int(plan.get("federation_coherence", 0) or 0),
        "federation_harmony": int(plan.get("federation_harmony", 0) or 0),
        "federation_pressure": int(plan.get("federation_pressure", 0) or 0),
        "federation_integrity": int(plan.get("federation_integrity", 0) or 0),
        "federation_resilience": int(plan.get("federation_resilience", 0) or 0),
        "federation_alignment": int(plan.get("federation_alignment", 0) or 0),
        "federation_divergence": int(plan.get("federation_divergence", 0) or 0),
        "runtime_continuity_profile": str(plan.get("runtime_continuity_profile") or "").strip(),
        "cinematic_runtime_state": str(plan.get("cinematic_runtime_state") or "").strip(),
        "orchestration_unity": str(plan.get("orchestration_unity") or "").strip(),
        "adaptive_federation_balance": int(plan.get("adaptive_federation_balance", 0) or 0),
        "runtime_phase_transition": str(plan.get("runtime_phase_transition") or "").strip(),
        "continuity_projection": str(plan.get("continuity_projection") or "").strip(),
        "federation_memory_summary": dict(plan.get("federation_memory_summary") or {}),
        "runtime_temporal": dict(plan.get("runtime_temporal") or {}),
        "temporal_state": dict(plan.get("temporal_state") or {}),
        "temporal_phase": dict(plan.get("temporal_phase") or {}),
        "temporal_rhythm": dict(plan.get("temporal_rhythm") or {}),
        "temporal_forecast": dict(plan.get("temporal_forecast") or {}),
        "temporal_continuity": dict(plan.get("temporal_continuity") or {}),
        "temporal_decay": dict(plan.get("temporal_decay") or {}),
        "temporal_recovery": dict(plan.get("temporal_recovery") or {}),
        "temporal_governance": dict(plan.get("temporal_governance") or {}),
        "temporal_metrics": dict(plan.get("temporal_metrics") or {}),
        "temporal_events": [dict(item) for item in (plan.get("temporal_events") or []) if isinstance(item, dict)],
        "temporal_integrity": int(plan.get("temporal_integrity", 0) or 0),
        "temporal_alignment": int(plan.get("temporal_alignment", 0) or 0),
        "temporal_stability": int(plan.get("temporal_stability", 0) or 0),
        "temporal_momentum": int(plan.get("temporal_momentum", 0) or 0),
        "temporal_pressure": int(plan.get("temporal_pressure", 0) or 0),
        "continuity_decay_rate": int(plan.get("continuity_decay_rate", 0) or 0),
        "runtime_rhythm_state": str(plan.get("runtime_rhythm_state") or "").strip(),
        "cinematic_temporal_flow": str(plan.get("cinematic_temporal_flow") or "").strip(),
        "orchestration_phase_velocity": str(plan.get("orchestration_phase_velocity") or "").strip(),
        "adaptive_temporal_balance": int(plan.get("adaptive_temporal_balance", 0) or 0),
        "runtime_cycle_phase": str(plan.get("runtime_cycle_phase") or "").strip(),
        "temporal_projection": str(plan.get("temporal_projection") or "").strip(),
        "temporal_memory_summary": dict(plan.get("temporal_memory_summary") or {}),
        "runtime_resonance": dict(plan.get("runtime_resonance") or {}),
        "resonance_state": dict(plan.get("resonance_state") or {}),
        "resonance_harmony": dict(plan.get("resonance_harmony") or {}),
        "resonance_sync": dict(plan.get("resonance_sync") or {}),
        "resonance_projection": dict(plan.get("resonance_projection") or {}),
        "resonance_equilibrium": dict(plan.get("resonance_equilibrium") or {}),
        "resonance_governance": dict(plan.get("resonance_governance") or {}),
        "resonance_metrics": dict(plan.get("resonance_metrics") or {}),
        "resonance_events": [dict(item) for item in (plan.get("resonance_events") or []) if isinstance(item, dict)],
        "resonance_recovery": dict(plan.get("resonance_recovery") or {}),
        "resonance_integrity": int(plan.get("resonance_integrity", 0) or 0),
        "resonance_alignment": int(plan.get("resonance_alignment", 0) or 0),
        "resonance_stability": int(plan.get("resonance_stability", 0) or 0),
        "resonance_pressure": int(plan.get("resonance_pressure", 0) or 0),
        "resonance_fragmentation": int(plan.get("resonance_fragmentation", 0) or 0),
        "resonance_cohesion": int(plan.get("resonance_cohesion", 0) or 0),
        "harmonic_runtime_state": str(plan.get("harmonic_runtime_state") or "").strip(),
        "cinematic_resonance": str(plan.get("cinematic_resonance") or "").strip(),
        "orchestration_resonance": str(plan.get("orchestration_resonance") or "").strip(),
        "adaptive_sync_balance": int(plan.get("adaptive_sync_balance", 0) or 0),
        "resonance_phase": str(plan.get("resonance_phase") or "").strip(),
        "sync_drift": int(plan.get("sync_drift", 0) or 0),
        "runtime_harmony_index": int(plan.get("runtime_harmony_index", 0) or 0),
        "resonance_memory_summary": dict(plan.get("resonance_memory_summary") or {}),
        "runtime_symbiosis": dict(plan.get("runtime_symbiosis") or {}),
        "symbiosis_state": dict(plan.get("symbiosis_state") or {}),
        "symbiosis_balance": dict(plan.get("symbiosis_balance") or {}),
        "symbiosis_cooperation": dict(plan.get("symbiosis_cooperation") or {}),
        "symbiosis_dependencies": dict(plan.get("symbiosis_dependencies") or {}),
        "symbiosis_recovery": dict(plan.get("symbiosis_recovery") or {}),
        "symbiosis_projection": dict(plan.get("symbiosis_projection") or {}),
        "symbiosis_equilibrium": dict(plan.get("symbiosis_equilibrium") or {}),
        "symbiosis_governance": dict(plan.get("symbiosis_governance") or {}),
        "symbiosis_metrics": dict(plan.get("symbiosis_metrics") or {}),
        "symbiosis_events": [dict(item) for item in (plan.get("symbiosis_events") or []) if isinstance(item, dict)],
        "symbiosis_integrity": int(plan.get("symbiosis_integrity", 0) or 0),
        "symbiosis_alignment": int(plan.get("symbiosis_alignment", 0) or 0),
        "symbiosis_stability": int(plan.get("symbiosis_stability", 0) or 0),
        "symbiosis_pressure": int(plan.get("symbiosis_pressure", 0) or 0),
        "symbiosis_mutualism": int(plan.get("symbiosis_mutualism", 0) or 0),
        "symbiosis_fragmentation": int(plan.get("symbiosis_fragmentation", 0) or 0),
        "cooperative_runtime_state": str(plan.get("cooperative_runtime_state") or "").strip(),
        "runtime_coexistence": str(plan.get("runtime_coexistence") or "").strip(),
        "adaptive_mutual_balance": str(plan.get("adaptive_mutual_balance") or "").strip(),
        "systemic_runtime_health": str(plan.get("systemic_runtime_health") or "").strip(),
        "recovery_cohesion": str(plan.get("recovery_cohesion") or "").strip(),
        "dependency_stress": int(plan.get("dependency_stress", 0) or 0),
        "symbiotic_phase": str(plan.get("symbiotic_phase") or "").strip(),
        "symbiosis_memory_summary": dict(plan.get("symbiosis_memory_summary") or {}),
    }


def _now_iso8601() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _json_safe_strings(values: list[Any]) -> list[str]:
    return [str(value or "").strip() for value in values if str(value or "").strip()]
